
//! Autogenerated weights for `pallet_launchpad`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2026-09-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `v-dex`, CPU: `Intel(R) Xeon(R) Platinum 8280 CPU @ 2.70GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/vitreus-power-plant-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution
// compiled
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --template
// .maintain/frame-weight-template.hbs
// --pallet
// pallet_launchpad
// --extrinsic
// *
// --output
// pallets/launchpad/src/weights.rs
// --json-file
// /tmp/bench-launchpad.json

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_launchpad`.
pub trait WeightInfo {
	fn create_launch(n: u32, s: u32, d: u32, u: u32, ) -> Weight;
	fn buy() -> Weight;
	fn buy_crossing() -> Weight;
	fn sell() -> Weight;
	fn graduate() -> Weight;
	fn claim_creator_fees() -> Weight;
	fn set_launch_metadata(d: u32, u: u32, ) -> Weight;
	fn set_creator_fee_recipient() -> Weight;
	fn set_params() -> Weight;
	fn set_creation_paused() -> Weight;
	fn force_seed_into_existing_pool() -> Weight;
}

/// Weights for `pallet_launchpad` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Launchpad::CreationPaused` (r:1 w:0)
	/// Proof: `Launchpad::CreationPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::NextLaunchId` (r:1 w:1)
	/// Proof: `Launchpad::NextLaunchId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::AssetToLaunch` (r:1 w:1)
	/// Proof: `Launchpad::AssetToLaunch` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Params` (r:1 w:0)
	/// Proof: `Launchpad::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:0)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:1 w:1)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:1)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `NacManaging::UsersNft` (r:0 w:1)
	/// Proof: `NacManaging::UsersNft` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Launches` (r:0 w:1)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:0 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Metadata` (r:0 w:1)
	/// Proof: `Launchpad::Metadata` (`max_values`: None, `max_size`: Some(2082), added: 4557, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:1)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 50]`.
	/// The range of component `s` is `[1, 50]`.
	/// The range of component `d` is `[0, 1024]`.
	/// The range of component `u` is `[0, 256]`.
	fn create_launch(_n: u32, _s: u32, _d: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2210`
		//  Estimated: `6172`
		// Minimum execution time: 286_042_000 picoseconds.
		Weight::from_parts(313_394_064, 6172)
			// Standard Error: 5_071
			.saturating_add(Weight::from_parts(4_331, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(16_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1413`
		//  Estimated: `6184`
		// Minimum execution time: 202_681_000 picoseconds.
		Weight::from_parts(216_602_000, 6184)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:2)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::DefaultFeeRouting` (r:1 w:0)
	/// Proof: `VitreusDex::DefaultFeeRouting` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:0 w:1)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:0 w:2)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `NacManaging::UsersNft` (r:0 w:1)
	/// Proof: `NacManaging::UsersNft` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::TotalLiquidity` (r:0 w:1)
	/// Proof: `VitreusDex::TotalLiquidity` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LiquidityPositions` (r:0 w:1)
	/// Proof: `VitreusDex::LiquidityPositions` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:1)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn buy_crossing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2771`
		//  Estimated: `11378`
		// Minimum execution time: 592_615_000 picoseconds.
		Weight::from_parts(606_943_000, 11378)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(22_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1476`
		//  Estimated: `6184`
		// Minimum execution time: 188_648_000 picoseconds.
		Weight::from_parts(191_028_000, 6184)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::DefaultFeeRouting` (r:1 w:0)
	/// Proof: `VitreusDex::DefaultFeeRouting` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:0 w:1)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:0 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `NacManaging::UsersNft` (r:0 w:1)
	/// Proof: `NacManaging::UsersNft` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::TotalLiquidity` (r:0 w:1)
	/// Proof: `VitreusDex::TotalLiquidity` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LiquidityPositions` (r:0 w:1)
	/// Proof: `VitreusDex::LiquidityPositions` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:1)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn graduate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2775`
		//  Estimated: `8781`
		// Minimum execution time: 423_352_000 picoseconds.
		Weight::from_parts(442_261_000, 8781)
			.saturating_add(T::DbWeight::get().reads(17_u64))
			.saturating_add(T::DbWeight::get().writes(19_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn claim_creator_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `665`
		//  Estimated: `3641`
		// Minimum execution time: 78_194_000 picoseconds.
		Weight::from_parts(87_697_000, 3641)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Metadata` (r:0 w:1)
	/// Proof: `Launchpad::Metadata` (`max_values`: None, `max_size`: Some(2082), added: 4557, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 1024]`.
	/// The range of component `u` is `[0, 256]`.
	fn set_launch_metadata(d: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `452`
		//  Estimated: `3641`
		// Minimum execution time: 24_508_000 picoseconds.
		Weight::from_parts(25_913_018, 3641)
			// Standard Error: 138
			.saturating_add(Weight::from_parts(1_548, 0).saturating_mul(d.into()))
			// Standard Error: 553
			.saturating_add(Weight::from_parts(2_975, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:1)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	fn set_creator_fee_recipient() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `419`
		//  Estimated: `3641`
		// Minimum execution time: 21_439_000 picoseconds.
		Weight::from_parts(22_788_000, 3641)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::Params` (r:0 w:1)
	/// Proof: `Launchpad::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn set_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_896_000 picoseconds.
		Weight::from_parts(8_323_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::CreationPaused` (r:0 w:1)
	/// Proof: `Launchpad::CreationPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_creation_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_427_000 picoseconds.
		Weight::from_parts(7_712_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::TotalLiquidity` (r:1 w:1)
	/// Proof: `VitreusDex::TotalLiquidity` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LiquidityPositions` (r:1 w:1)
	/// Proof: `VitreusDex::LiquidityPositions` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn force_seed_into_existing_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1938`
		//  Estimated: `8781`
		// Minimum execution time: 262_329_000 picoseconds.
		Weight::from_parts(275_872_000, 8781)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Launchpad::CreationPaused` (r:1 w:0)
	/// Proof: `Launchpad::CreationPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::NextLaunchId` (r:1 w:1)
	/// Proof: `Launchpad::NextLaunchId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::AssetToLaunch` (r:1 w:1)
	/// Proof: `Launchpad::AssetToLaunch` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Params` (r:1 w:0)
	/// Proof: `Launchpad::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:0)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:1 w:1)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:1)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `NacManaging::UsersNft` (r:0 w:1)
	/// Proof: `NacManaging::UsersNft` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Launches` (r:0 w:1)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:0 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Metadata` (r:0 w:1)
	/// Proof: `Launchpad::Metadata` (`max_values`: None, `max_size`: Some(2082), added: 4557, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:1)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 50]`.
	/// The range of component `s` is `[1, 50]`.
	/// The range of component `d` is `[0, 1024]`.
	/// The range of component `u` is `[0, 256]`.
	fn create_launch(_n: u32, _s: u32, _d: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2210`
		//  Estimated: `6172`
		// Minimum execution time: 286_042_000 picoseconds.
		Weight::from_parts(313_394_064, 6172)
			// Standard Error: 5_071
			.saturating_add(Weight::from_parts(4_331, 0).saturating_mul(u.into()))
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(16_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn buy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1413`
		//  Estimated: `6184`
		// Minimum execution time: 202_681_000 picoseconds.
		Weight::from_parts(216_602_000, 6184)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:2)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::DefaultFeeRouting` (r:1 w:0)
	/// Proof: `VitreusDex::DefaultFeeRouting` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:0 w:1)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:0 w:2)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `NacManaging::UsersNft` (r:0 w:1)
	/// Proof: `NacManaging::UsersNft` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::TotalLiquidity` (r:0 w:1)
	/// Proof: `VitreusDex::TotalLiquidity` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LiquidityPositions` (r:0 w:1)
	/// Proof: `VitreusDex::LiquidityPositions` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:1)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn buy_crossing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2771`
		//  Estimated: `11378`
		// Minimum execution time: 592_615_000 picoseconds.
		Weight::from_parts(606_943_000, 11378)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(22_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn sell() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1476`
		//  Estimated: `6184`
		// Minimum execution time: 188_648_000 picoseconds.
		Weight::from_parts(191_028_000, 6184)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::DefaultFeeRouting` (r:1 w:0)
	/// Proof: `VitreusDex::DefaultFeeRouting` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:1 w:1)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:0 w:1)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:0 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `NacManaging::UsersNft` (r:0 w:1)
	/// Proof: `NacManaging::UsersNft` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::TotalLiquidity` (r:0 w:1)
	/// Proof: `VitreusDex::TotalLiquidity` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LiquidityPositions` (r:0 w:1)
	/// Proof: `VitreusDex::LiquidityPositions` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:1)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn graduate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2775`
		//  Estimated: `8781`
		// Minimum execution time: 423_352_000 picoseconds.
		Weight::from_parts(442_261_000, 8781)
			.saturating_add(RocksDbWeight::get().reads(17_u64))
			.saturating_add(RocksDbWeight::get().writes(19_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn claim_creator_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `665`
		//  Estimated: `3641`
		// Minimum execution time: 78_194_000 picoseconds.
		Weight::from_parts(87_697_000, 3641)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Metadata` (r:0 w:1)
	/// Proof: `Launchpad::Metadata` (`max_values`: None, `max_size`: Some(2082), added: 4557, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 1024]`.
	/// The range of component `u` is `[0, 256]`.
	fn set_launch_metadata(d: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `452`
		//  Estimated: `3641`
		// Minimum execution time: 24_508_000 picoseconds.
		Weight::from_parts(25_913_018, 3641)
			// Standard Error: 138
			.saturating_add(Weight::from_parts(1_548, 0).saturating_mul(d.into()))
			// Standard Error: 553
			.saturating_add(Weight::from_parts(2_975, 0).saturating_mul(u.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:1)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	fn set_creator_fee_recipient() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `419`
		//  Estimated: `3641`
		// Minimum execution time: 21_439_000 picoseconds.
		Weight::from_parts(22_788_000, 3641)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::Params` (r:0 w:1)
	/// Proof: `Launchpad::Params` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn set_params() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_896_000 picoseconds.
		Weight::from_parts(8_323_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::CreationPaused` (r:0 w:1)
	/// Proof: `Launchpad::CreationPaused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_creation_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_427_000 picoseconds.
		Weight::from_parts(7_712_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(176), added: 2651, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:1)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(115), added: 2590, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(126), added: 2601, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::TotalLiquidity` (r:1 w:1)
	/// Proof: `VitreusDex::TotalLiquidity` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LiquidityPositions` (r:1 w:1)
	/// Proof: `VitreusDex::LiquidityPositions` (`max_values`: None, `max_size`: Some(111), added: 2586, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::ProtocolFeeRecipient` (r:1 w:0)
	/// Proof: `VitreusDex::ProtocolFeeRecipient` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn force_seed_into_existing_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1938`
		//  Estimated: `8781`
		// Minimum execution time: 262_329_000 picoseconds.
		Weight::from_parts(275_872_000, 8781)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
	}
}
