
//! Autogenerated weights for `pallet_launch_treasury`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2026-09-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-c-16-nyc1`, CPU: `Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/vitreus-power-plant-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution
// compiled
// --steps
// 50
// --repeat
// 20
// --heap-pages
// 4096
// --template
// .maintain/frame-weight-template.hbs
// --pallet
// pallet_launch_treasury
// --extrinsic
// *
// --output
// pallets/launch-treasury/src/weights.rs
// --json-file
// /tmp/bench-launch-treasury.json

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_launch_treasury`.
pub trait WeightInfo {
	fn stake() -> Weight;
	fn retarget() -> Weight;
	fn harvest() -> Weight;
	fn compound() -> Weight;
	fn retire() -> Weight;
	fn finalize_retirement(n: u32, ) -> Weight;
	fn set_terms() -> Weight;
	fn set_targets() -> Weight;
}

/// Weights for `pallet_launch_treasury` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `LaunchTreasury::Treasuries` (r:1 w:1)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Terms` (r:1 w:0)
	/// Proof: `LaunchTreasury::Terms` (`max_values`: Some(1), `max_size`: Some(28), added: 523, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:1)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:1)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1287), added: 3762, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:1 w:0)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7180`
		//  Estimated: `43864`
		// Minimum execution time: 561_528_000 picoseconds.
		Weight::from_parts(594_705_000, 43864)
			.saturating_add(T::DbWeight::get().reads(66_u64))
			.saturating_add(T::DbWeight::get().writes(26_u64))
	}
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:0)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:1 w:0)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn retarget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5947`
		//  Estimated: `43864`
		// Minimum execution time: 443_004_000 picoseconds.
		Weight::from_parts(464_621_000, 43864)
			.saturating_add(T::DbWeight::get().reads(57_u64))
			.saturating_add(T::DbWeight::get().writes(19_u64))
	}
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:0)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn harvest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `666`
		//  Estimated: `3587`
		// Minimum execution time: 41_541_000 picoseconds.
		Weight::from_parts(42_729_000, 3587)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `LaunchTreasury::Treasuries` (r:1 w:1)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Terms` (r:1 w:0)
	/// Proof: `LaunchTreasury::Terms` (`max_values`: Some(1), `max_size`: Some(28), added: 523, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:0)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `DynamicEnergy::ExchangeRate` (r:1 w:0)
	/// Proof: `DynamicEnergy::ExchangeRate` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:3 w:3)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:4 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EnergyBroker::EnergyCapacity` (r:1 w:0)
	/// Proof: `EnergyBroker::EnergyCapacity` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `DynamicEnergy::SessionEnergySale` (r:1 w:1)
	/// Proof: `DynamicEnergy::SessionEnergySale` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:0)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:0 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LastSwapBlock` (r:0 w:1)
	/// Proof: `VitreusDex::LastSwapBlock` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn compound() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3197`
		//  Estimated: `13975`
		// Minimum execution time: 608_440_000 picoseconds.
		Weight::from_parts(652_665_000, 13975)
			.saturating_add(T::DbWeight::get().reads(26_u64))
			.saturating_add(T::DbWeight::get().writes(19_u64))
	}
	/// Storage: `LaunchTreasury::Treasuries` (r:1 w:1)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:0)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:0)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LastSwapBlock` (r:1 w:0)
	/// Proof: `VitreusDex::LastSwapBlock` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:1)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:1)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::RetiringQueue` (r:1 w:1)
	/// Proof: `LaunchTreasury::RetiringQueue` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::CurrentDate` (r:1 w:0)
	/// Proof: `Privileges::CurrentDate` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1287), added: 3762, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:1 w:0)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn retire() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8073`
		//  Estimated: `43864`
		// Minimum execution time: 628_799_000 picoseconds.
		Weight::from_parts(676_671_000, 43864)
			.saturating_add(T::DbWeight::get().reads(71_u64))
			.saturating_add(T::DbWeight::get().writes(27_u64))
	}
	/// Storage: `LaunchTreasury::Treasuries` (r:64 w:64)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:1)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:1)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::SlashingSpans` (r:1 w:0)
	/// Proof: `EnergyGeneration::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EnergyGeneration::Validators` (r:1 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:0)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1287), added: 3762, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::RetiringQueue` (r:1 w:1)
	/// Proof: `LaunchTreasury::RetiringQueue` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Payee` (r:0 w:1)
	/// Proof: `EnergyGeneration::Payee` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 64]`.
	fn finalize_retirement(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460 + n * (150 ±0)`
		//  Estimated: `12716 + n * (2584 ±0)`
		// Minimum execution time: 122_978_000 picoseconds.
		Weight::from_parts(130_154_179, 12716)
			// Standard Error: 43_382
			.saturating_add(Weight::from_parts(9_956_914, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2584).saturating_mul(n.into()))
	}
	/// Storage: `LaunchTreasury::Terms` (r:0 w:1)
	/// Proof: `LaunchTreasury::Terms` (`max_values`: Some(1), `max_size`: Some(28), added: 523, mode: `MaxEncodedLen`)
	fn set_terms() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_009_000 picoseconds.
		Weight::from_parts(8_641_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:0)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:0 w:1)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	fn set_targets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4028`
		//  Estimated: `43864`
		// Minimum execution time: 403_173_000 picoseconds.
		Weight::from_parts(437_769_000, 43864)
			.saturating_add(T::DbWeight::get().reads(56_u64))
			.saturating_add(T::DbWeight::get().writes(20_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `LaunchTreasury::Treasuries` (r:1 w:1)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Terms` (r:1 w:0)
	/// Proof: `LaunchTreasury::Terms` (`max_values`: Some(1), `max_size`: Some(28), added: 523, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:1)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:1)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1287), added: 3762, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:1 w:0)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7180`
		//  Estimated: `43864`
		// Minimum execution time: 561_528_000 picoseconds.
		Weight::from_parts(594_705_000, 43864)
			.saturating_add(RocksDbWeight::get().reads(66_u64))
			.saturating_add(RocksDbWeight::get().writes(26_u64))
	}
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:0)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:1 w:0)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn retarget() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5947`
		//  Estimated: `43864`
		// Minimum execution time: 443_004_000 picoseconds.
		Weight::from_parts(464_621_000, 43864)
			.saturating_add(RocksDbWeight::get().reads(57_u64))
			.saturating_add(RocksDbWeight::get().writes(19_u64))
	}
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:0)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn harvest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `666`
		//  Estimated: `3587`
		// Minimum execution time: 41_541_000 picoseconds.
		Weight::from_parts(42_729_000, 3587)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `LaunchTreasury::Treasuries` (r:1 w:1)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Terms` (r:1 w:0)
	/// Proof: `LaunchTreasury::Terms` (`max_values`: Some(1), `max_size`: Some(28), added: 523, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:0)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `DynamicEnergy::ExchangeRate` (r:1 w:0)
	/// Proof: `DynamicEnergy::ExchangeRate` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:3 w:3)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:4 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EnergyBroker::EnergyCapacity` (r:1 w:0)
	/// Proof: `EnergyBroker::EnergyCapacity` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `DynamicEnergy::SessionEnergySale` (r:1 w:1)
	/// Proof: `DynamicEnergy::SessionEnergySale` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:0)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:1)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:0 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LastSwapBlock` (r:0 w:1)
	/// Proof: `VitreusDex::LastSwapBlock` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	fn compound() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3197`
		//  Estimated: `13975`
		// Minimum execution time: 608_440_000 picoseconds.
		Weight::from_parts(652_665_000, 13975)
			.saturating_add(RocksDbWeight::get().reads(26_u64))
			.saturating_add(RocksDbWeight::get().writes(19_u64))
	}
	/// Storage: `LaunchTreasury::Treasuries` (r:1 w:1)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Curves` (r:1 w:0)
	/// Proof: `Launchpad::Curves` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `Launchpad::Launches` (r:1 w:0)
	/// Proof: `Launchpad::Launches` (`max_values`: None, `max_size`: Some(178), added: 2653, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::Pools` (r:1 w:0)
	/// Proof: `VitreusDex::Pools` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `VitreusDex::LastSwapBlock` (r:1 w:0)
	/// Proof: `VitreusDex::LastSwapBlock` (`max_values`: None, `max_size`: Some(54), added: 2529, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(122), added: 2597, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgAccounted` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgAccounted` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::TotalShares` (r:1 w:1)
	/// Proof: `LaunchTreasury::TotalShares` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::LnrgPerShare` (r:1 w:1)
	/// Proof: `LaunchTreasury::LnrgPerShare` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:1)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::RetiringQueue` (r:1 w:1)
	/// Proof: `LaunchTreasury::RetiringQueue` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::CurrentDate` (r:1 w:0)
	/// Proof: `Privileges::CurrentDate` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1287), added: 3762, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:1 w:0)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn retire() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8073`
		//  Estimated: `43864`
		// Minimum execution time: 628_799_000 picoseconds.
		Weight::from_parts(676_671_000, 43864)
			.saturating_add(RocksDbWeight::get().reads(71_u64))
			.saturating_add(RocksDbWeight::get().writes(27_u64))
	}
	/// Storage: `LaunchTreasury::Treasuries` (r:64 w:64)
	/// Proof: `LaunchTreasury::Treasuries` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:1)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:1)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::SlashingSpans` (r:1 w:0)
	/// Proof: `EnergyGeneration::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `EnergyGeneration::Validators` (r:1 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:0)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1287), added: 3762, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(173), added: 2648, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::RetiringQueue` (r:1 w:1)
	/// Proof: `LaunchTreasury::RetiringQueue` (`max_values`: Some(1), `max_size`: Some(1794), added: 2289, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Payee` (r:0 w:1)
	/// Proof: `EnergyGeneration::Payee` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 64]`.
	fn finalize_retirement(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1460 + n * (150 ±0)`
		//  Estimated: `12716 + n * (2584 ±0)`
		// Minimum execution time: 122_978_000 picoseconds.
		Weight::from_parts(130_154_179, 12716)
			// Standard Error: 43_382
			.saturating_add(Weight::from_parts(9_956_914, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2584).saturating_mul(n.into()))
	}
	/// Storage: `LaunchTreasury::Terms` (r:0 w:1)
	/// Proof: `LaunchTreasury::Terms` (`max_values`: Some(1), `max_size`: Some(28), added: 523, mode: `MaxEncodedLen`)
	fn set_terms() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_009_000 picoseconds.
		Weight::from_parts(8_641_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `EnergyGeneration::Bonded` (r:1 w:0)
	/// Proof: `EnergyGeneration::Bonded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Ledger` (r:1 w:0)
	/// Proof: `EnergyGeneration::Ledger` (`max_values`: None, `max_size`: Some(1708), added: 4183, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::MinCooperatorBond` (r:1 w:0)
	/// Proof: `EnergyGeneration::MinCooperatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Validators` (r:17 w:0)
	/// Proof: `EnergyGeneration::Validators` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Reputation::AccountReputation` (r:17 w:0)
	/// Proof: `Reputation::AccountReputation` (`max_values`: None, `max_size`: Some(47), added: 2522, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Cooperators` (r:1 w:1)
	/// Proof: `EnergyGeneration::Cooperators` (`max_values`: None, `max_size`: Some(9251), added: 11726, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::CurrentEra` (r:1 w:0)
	/// Proof: `EnergyGeneration::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EnergyGeneration::Collaborations` (r:16 w:16)
	/// Proof: `EnergyGeneration::Collaborations` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Privileges::VipMembers` (r:1 w:1)
	/// Proof: `Privileges::VipMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `LaunchTreasury::CooperationStale` (r:0 w:1)
	/// Proof: `LaunchTreasury::CooperationStale` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `LaunchTreasury::Targets` (r:0 w:1)
	/// Proof: `LaunchTreasury::Targets` (`max_values`: Some(1), `max_size`: Some(321), added: 816, mode: `MaxEncodedLen`)
	fn set_targets() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4028`
		//  Estimated: `43864`
		// Minimum execution time: 403_173_000 picoseconds.
		Weight::from_parts(437_769_000, 43864)
			.saturating_add(RocksDbWeight::get().reads(56_u64))
			.saturating_add(RocksDbWeight::get().writes(20_u64))
	}
}
